<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogPostRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAllForList()
  {
      $qb = $this->createQueryBuilder('c');

      $qb
          ->select('c')
          ->addOrderBy('c.publishAt', 'DESC')
      ;

      return $qb->getQuery()->getResult();
}
}
